### PR TITLE
Fix shellcheck warnings and errors

### PR DESCRIPTION
**Pull request by guillaumealgis**
This :

- Adds a GitHub Action to run shellcheck on master and PRs
- Fixes all warnings and errors of shellcheck

The problems I saw the most were :

-  Double quoting of variables
    - https://www.shellcheck.net/wiki/SC2068
    - https://www.shellcheck.net/wiki/SC2046
    - https://www.shellcheck.net/wiki/SC2206
    - https://www.shellcheck.net/wiki/SC2086
- Usage of `` `cmd ...` `` over `$(cmd ...)`
    - https://www.shellcheck.net/wiki/SC2006
- Usage of `cd` and executing command without checking if the directory actually changed
    - https://www.shellcheck.net/wiki/SC2164

The diff is quite long but should be relatively straightforward to review. Let me know if anything isn't clear :)

### CODE REVIEW

**Comment by faithfracture** [comment]
This looks OK to me, but could you also submit your PR for #45 so I can actually build & test everything?

**Comment by guillaumealgis** [comment]
I'm a bit reluctant to open another PR before this one is merged because there's a lot of changes here so I'd be building on sand in another PR.

But you can build the project with juste a few patches :

First you'll have to fix `MACOS_SDK_VERSION` because Xcode 11.4 now includes the patch number in its output :

```diff
< MACOS_SDK_VERSION=$(xcrun --sdk macosx --show-sdk-version)
> MACOS_SDK_VERSION=$(xcrun --sdk macosx --show-sdk-version | awk -F. '{ print $1 "." $2 }')
```

Then download and apply the patch linked by @mjpan in https://github.com/faithfracture/Apple-Boost-BuildScript/issues/45 :

```bash
curl 'https://raw.githubusercontent.com/apache/kudu/e6fa761a4a60118bb61883fe8342943253f350d2/thirdparty/patches/boost-issue-440-darwin-version.patch' | patch -p0 -d src/boost_1_72_0
```

And it should build :)

**Comment by faithfracture** [comment]
Ok great, that's working fine, thanks!

Please update the changelog and I'll merge this. :) 

FYI, when you _do_ submit a PR for that patch, I don't want it to be pulled from that URL - I'm going to want it to be a local patch file added to the repository so this won't break if that repository goes away some day. I've already done this on my end, so if you'd rather I just commit that change I can.

**Comment by guillaumealgis** [comment]
> Please update the changelog and I'll merge this. :)

Sure, done.

> FYI, when you do submit a PR for that patch, I don't want it to be pulled from that URL - I'm going to want it to be a local patch file added to the repository so this won't break if that repository goes away some day.

Yup, it's what I had in mind too, the curl thing was just for a quick fix.

> I've already done this on my end, so if you'd rather I just commit that change I can.

Well if you've already done it, sure, there's no benefits to do the work twice :)

**Pull request merged**
